version: '2'

services:
  nginx:
    container_name: grid_nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - lognet

  php:
    container_name: grid_php
    build: images/php
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    depends_on:
      - db
      - cache
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: lumen
      DB_USERNAME: lumen
      DB_PASSWORD: secret
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      - lognet

  db:
    container_name: grid_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumen
      MYSQL_PASSWORD: secret
    networks:
      - lognet

  cache:
    container_name: grid_cache
    image: memcached
    networks:
      - lognet

networks:
  lognet:
    driver: bridge